signal: contador_varios_manejadores.c contador_un_manejador.c
	if [ ! -d "../bin" ]; then mkdir ../bin; fi
	gcc -o ../bin/contador_varios_manejadores contador_varios_manejadores.c
	gcc -o ../bin/contador_un_manejador contador_un_manejador.c
